# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d20dd119f76b17f6c45da8c58240a9b45362c79035272e037356df1160fb6d338ebfa8ffbb934cfd8298315fe8695ed8465d08f8275fe06b27169f2e79e55b7f

test:
  secret_key_base: d6f3b9d135393d3937d13d3295cd4f5f6c50a58caef3baef2144b514cfbee2247d8cce307e6f4b8b953416bc1015739327b7b50c51584eb48a40282681039d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
